### ISSUE TITLE
At open a browsing table i get: AttributeError: frameform has no attribute 'setHelperData' 

### ISSUE THREAD

**Issue by marcobra** [genropy/genropy#28]
```AttributeError

AttributeError: frameform has no attribute 'setHelperData' 
Traceback (most recent call last)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwsgisite.py", line 188, in __call__

    return self.wsgiapp(environ, start_response)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwsgisite.py", line 822, in dispatcher

    return self._dispatcher(environ, start_response)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwsgisite.py", line 1005, in _dispatcher

    result = page()

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwebpage.py", line 516, in __call__

    result = self._call_handler(*args, **kwargs)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwebpage.py", line 545, in _rpcDispatcher

    result = self.rpc(method=method, _auth=auth, **kwargs)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwebpage_proxy/rpc.py", line 42, in __call__

    result = handler(**kwargs)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwebpage.py", line 2195, in rpc_main

    self.main(rootwdg, **kwargs)

    File "/home/ubuntu/gnrv/genropy/projects/gnrcore/packages/sys/webpages/thpage.py", line 66, in main

    root.rootTableHandler(th_pkey=th_pkey,**kwargs)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwebstruct.py", line 319, in <lambda>

    return lambda *args, **kwargs: handler(self, *args,**kwargs)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/core/gnrdecorator.py", line 165, in newFunc

    return func(self,*args,**kwargs)

    File "/home/ubuntu/gnrv/genropy/resources/common/public.py", line 411, in pbl_rootTableHandler

    return self._th_main(root,th_options=th_options,**kwargs)

    File "/home/ubuntu/gnrv/genropy/resources/common/public.py", line 463, in _th_main

    th = getattr(root,'%sTableHandler' %thwidget)(table=self.maintable,datapath=tablecode,lockable=lockable,

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwebstruct.py", line 319, in <lambda>

    return lambda *args, **kwargs: handler(self, *args,**kwargs)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/core/gnrdecorator.py", line 165, in newFunc

    return func(self,*args,**kwargs)

    File "/home/ubuntu/gnrv/genropy/resources/common/th/th.py", line 371, in th_stackTableHandler

    form = wdg.tableEditor(frameCode=wdg.attributes['thform_root'],formRoot=wdg,pageName='form',formResource=formResource,

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwebstruct.py", line 319, in <lambda>

    return lambda *args, **kwargs: handler(self, *args,**kwargs)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/core/gnrdecorator.py", line 165, in newFunc

    return func(self,*args,**kwargs)

    File "/home/ubuntu/gnrv/genropy/resources/common/th/th_form.py", line 53, in th_tableEditor

    return self.th_finalizeForm(form,table=table,options=options,frameCode=frameCode)

    File "/home/ubuntu/gnrv/genropy/resources/common/th/th_form.py", line 84, in th_finalizeForm

    self._th_prepareFormDataHelper(form)

    File "/home/ubuntu/gnrv/genropy/resources/common/th/th_form.py", line 78, in _th_prepareFormDataHelper

    form.setHelperData(table=tbl)

    File "/home/ubuntu/gnrv/lib/python3.10/site-packages/gnr/web/gnrwebstruct.py", line 333, in __getattr__

    raise AttributeError("%s has no attribute '%s' " % (parentTag or repr(self), fname))

    AttributeError: frameform has no attribute 'setHelperData' ```

**Comment by marcobra** [comment]
today doing the steps below: 
```
git pull (with updates) 
pip install .
cd genropy/gnrpy/
gnr app dbsetup nomemiaapp
gnr web wsgiserve nomemiaapp
```
all is working
