### ISSUE TITLE
[psycopg v3] Errore in apertura pagina "Preferences"

### ISSUE THREAD

**Issue by EdoFede** [genropy/genropy#33]
Dopo switch a psycopg3, aprendo la pagina Preferences su una qualsiasi istanza, ottengo l'errore sotto.

### Ambiente
Intel Mac
macOS Sequoia 15.0.1 (24A348)
Python 3.13.0
Branch genropy: develop

### Errore
```python
Traceback (most recent call last):
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/web/gnrwsgisite.py", line 188, in __call__
    return self.wsgiapp(environ, start_response)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/web/gnrwsgisite.py", line 822, in dispatcher
    return self._dispatcher(environ, start_response)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/web/gnrwsgisite.py", line 1018, in _dispatcher
    result = page()
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/web/gnrwebpage.py", line 526, in __call__
    result = self._call_handler(*args, **kwargs)
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/web/gnrwebpage.py", line 555, in _rpcDispatcher
    result = self.rpc(method=method, _auth=auth, **kwargs)
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/web/gnrwebpage_proxy/rpc.py", line 42, in __call__
    result = handler(**kwargs)
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/web/gnrwebpage.py", line 2276, in rpc_main
    self.main(rootwdg, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/projects/gnrcore/packages/adm/webpages/app_preference.py", line 30, in main
    form.center.appPreferencesTabs(datapath='#FORM.record.data',margin='2px',wdg='stack')
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/web/gnrwebstruct.py", line 319, in <lambda>
    return lambda *args, **kwargs: handler(self, *args,**kwargs)
                                   ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/projects/gnrcore/packages/adm/resources/prefhandler/prefhandler.py", line 59, in ph_appPreferencesTabs
    tc = self._pr_makePreferenceTabs(parent,packages=packages,datapath=datapath,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/projects/gnrcore/packages/adm/resources/prefhandler/prefhandler.py", line 48, in _pr_makePreferenceTabs
    panecb(tc, title=pkg.attributes.get('name_full') or pkg.attributes.get('name_long') or pkg.id, datapath='.%s' % pkg.id, nodeId=pkg.id,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/projects/gnrcore/packages/adm/resources/preference.py", line 39, in prefpane_adm
    self._adm_privacy(tc.borderContainer(title='!!Privacy', datapath='.privacy'))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/projects/gnrcore/packages/adm/resources/preference.py", line 59, in _adm_privacy
    self.privacyPreferencePane(bc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "/Users/Edo/Documents/Genropy/genropy/projects/gnrcore/packages/adm/resources/privacy.py", line 7, in privacyPreferencePane
    self.privacyText(bc.contentPane(region='center'))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/projects/gnrcore/packages/adm/resources/privacy.py", line 11, in privacyText
    pane.ckeditor(value='^.privacy_policy', **kwargs)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/web/gnrwebstruct.py", line 1541, in ckeditor
    customStyles = style_table.getCustomStyles(stylegroup=stylegroup)
  File "/Users/Edo/Documents/Genropy/genropy/projects/gnrcore/packages/adm/model/ckstyle.py", line 22, in getCustomStyles
    columns='$name,$element,$styles,$attributes,$sgroup').fetchGrouped('sgroup')
                                                          ~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/sql/gnrsqldata.py", line 1114, in fetchGrouped
    fetch = self.fetch()
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/sql/gnrsqldata.py", line 1033, in fetch
    cursor = self.cursor()
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/sql/gnrsqldata.py", line 1029, in cursor
    return self.db.execute(self.sqltext, self.sqlparams, dbtable=self.dbtable.fullname,storename=self.storename)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/sql/gnrsql.py", line 487, in execute
    sql, sqlargs = self.adapter.prepareSqlText(sql, sqlargs)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/sql/adapters/gnrpostgres3.py", line 138, in prepareSqlText
    sqltext = RE_SQL_PARAMS.sub(subArgs, sqltext)
  File "/Users/Edo/Documents/Genropy/genropy/gnrpy/gnr/sql/adapters/gnrpostgres3.py", line 134, in subArgs
    sqlargs[key]=kwargs[key]
                 ~~~~~~^^^^^
KeyError: 'gr'
```

**Comment by EdoFede** [comment]
Stesso identico errore anche aprendo la vista "Tipi prodotto" su un'istanza sandbox(pg) vuota
