### ISSUE TITLE
Internal server error using the sandbox , TypeError: can only concatenate list (not "int") to list

### ISSUE THREAD

**Issue by biank88** [genropy/genropy#4]
**OS:** Linux mintVB 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

fra@mintVB ~/genropy/projects $ gnrwsgiserve sandbox/

```
serving on 0.0.0.0:8080 view at http://127.0.0.1:8080
\----------------------------------------
Exception happened during processing of request from ('192.168.0.100', 55328)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/usr/local/lib/python2.7/dist-packages/paste/httpserver.py", line 304, in wsgi_execute
    self.wsgi_start_response)
  File "/home/fra/genropy/gnrpy/gnr/web/gnrwsgisite.py", line 179, in __call__
    return self.wsgiapp(environ, start_response)
  File "/home/fra/genropy/gnrpy/gnr/web/gnrwsgisite.py", line 140, in __call__
    return super(SafeEvalException, self).__call__(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/weberror/evalexception.py", line 257, in __call__
    req_path = req.path_info.split('/')[1:len(self.debug_url_prefix + 1)]
TypeError: can only concatenate list (not "int") to list
\----------------------------------------
```

**Comment by biank88** [comment]
cercando su google ho trovato un fix proposto dagli sviluppatori:
https://www.freelists.org/post/genropy/Installazione-sul-mio-serverino-non-funzionante,6

> rimuovere weberror con:
sudo pip uninstall weberror
E reinstallare la versione precedente:
sudo pip install weberror==0.12

a questo punto, sarebbe però opportuno aggiornare i requirements del progetto.
credo che problemi del genere siano abbastanza sgradevoli per un beginner.
